# Generated by Django 5.0.6 on 2024-05-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='slud',
            new_name='slug',
        ),
    ]
