# Generated by Django 5.0.6 on 2024-05-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contect',
            new_name='content',
        ),
    ]
